name: Zchat
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
packages: {}
targets:
  Zchat:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: Sources
    resources:
      - path: Resources
    info:
      path: Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        NSBluetoothAlwaysUsageDescription: "Bluetooth is used for nearby offline messaging."
        NSBluetoothPeripheralUsageDescription: "Bluetooth is used for nearby offline messaging."
        UIRequiresFullScreen: true
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.zchat
        INFOPLIST_FILE: Info.plist
